//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailModule.Projects {
    
    public partial class AddTask {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Label lblMsg;
        protected System.Web.UI.WebControls.Label lblProject;
        protected System.Web.UI.WebControls.DropDownList ddlProject;
        protected System.Web.UI.WebControls.Label lblModule;
        protected System.Web.UI.WebControls.DropDownList ddlModule;
        protected System.Web.UI.WebControls.Label lblName;
        protected System.Web.UI.WebControls.TextBox txtName;
        protected System.Web.UI.WebControls.Label lblDesc;
        protected System.Web.UI.WebControls.TextBox txtDesc;
        protected System.Web.UI.WebControls.Label lblType;
        protected System.Web.UI.WebControls.DropDownList ddlType;
        protected System.Web.UI.WebControls.Label lblPriority;
        protected System.Web.UI.WebControls.DropDownList ddlPriority;
        protected System.Web.UI.WebControls.Label lblHour;
        protected System.Web.UI.WebControls.TextBox txtHour;
        protected System.Web.UI.WebControls.Label lblCurStatus;
        protected System.Web.UI.WebControls.DropDownList ddlCurStatus;
        protected System.Web.UI.WebControls.Button btnSave;
        protected System.Web.UI.WebControls.Button btnCancel;
    }
}
