//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailModule.Projects {
    
    public partial class Tasks {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected EmailModule.Email.UserControl.Menu Menu1;
        protected System.Web.UI.WebControls.Label lblModule;
        protected System.Web.UI.WebControls.DropDownList ddlModule;
        protected System.Web.UI.WebControls.Label lblType;
        protected System.Web.UI.WebControls.DropDownList ddlType;
        protected System.Web.UI.WebControls.Label lblPriority;
        protected System.Web.UI.WebControls.DropDownList ddlPriority;
        protected System.Web.UI.WebControls.Label lblCurStatus;
        protected System.Web.UI.WebControls.DropDownList ddlCurStatus;
        protected System.Web.UI.WebControls.Button btnSearch;
        protected System.Web.UI.WebControls.HyperLink hlNewTask;
        protected System.Web.UI.WebControls.HyperLink HyperLink1;
        protected System.Web.UI.WebControls.HyperLink hlNewModule;
        protected System.Web.UI.WebControls.HyperLink hlNewProject;
        protected System.Web.UI.WebControls.GridView grdTasks;
        protected System.Web.UI.WebControls.Label lbltxtGridTotalHour;
        protected System.Web.UI.WebControls.Label lblGridTotalHour;
        protected System.Web.UI.WebControls.Label lbltxtGridTotalBill;
        protected System.Web.UI.WebControls.Label lblGridTotalBill;
        protected System.Web.UI.WebControls.Label lblPayInternalHour;
        protected System.Web.UI.WebControls.Label lbltxtPayInternalHour;
        protected System.Web.UI.WebControls.Label lblICharge;
        protected System.Web.UI.WebControls.Label lbltxtICharge;
        protected System.Web.UI.WebControls.Label lblMaintenanceHour;
        protected System.Web.UI.WebControls.Label lbltxtMaintenanceHour;
        protected System.Web.UI.WebControls.Label lblMCharge;
        protected System.Web.UI.WebControls.Label lbltxtMCharge;
        protected System.Web.UI.WebControls.Label lblDevelopmentHour;
        protected System.Web.UI.WebControls.Label lbltxtDevelopmentHour;
        protected System.Web.UI.WebControls.Label lblDCharge;
        protected System.Web.UI.WebControls.Label lbltxtDCharge;
        protected System.Web.UI.WebControls.Label lbltxtTotalHour;
        protected System.Web.UI.WebControls.Label lblTotalHour;
        protected System.Web.UI.WebControls.Label lbltxtTotalBill;
        protected System.Web.UI.WebControls.Label lblTotalBill;
        protected System.Web.UI.WebControls.Label lbltxtPaid;
        protected System.Web.UI.WebControls.Label lblPaid;
        protected System.Web.UI.WebControls.Label lblPayAmount;
        protected System.Web.UI.WebControls.TextBox txtPayAmount;
        protected System.Web.UI.WebControls.Label lblPayDate;
        protected System.Web.UI.WebControls.TextBox txtPayDate;
        protected System.Web.UI.WebControls.Label lblPayComment;
        protected System.Web.UI.WebControls.TextBox txtPayComment;
        protected System.Web.UI.WebControls.Button btnAddPayment;
        protected System.Web.UI.WebControls.Label lbltxtBalance;
        protected System.Web.UI.WebControls.Label lblBalance;
        protected System.Web.UI.WebControls.SqlDataSource dsPayment;
        protected System.Web.UI.WebControls.GridView grdPaymentList;
        protected System.Web.UI.WebControls.SqlDataSource dsPaymentListing;
        protected System.Web.UI.WebControls.TextBox txtNotes;
        protected System.Web.UI.WebControls.Button btnUpdateNote;
        protected System.Web.UI.WebControls.SqlDataSource dsNote;
        protected System.Web.UI.WebControls.SqlDataSource dsSaveNote;
    }
}
