//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailModule.Email {
    
    public partial class AutoSchedule {
        protected EmailModule.Email.UserControl.Menu Menu1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Label lblAcive;
        protected System.Web.UI.WebControls.DropDownList ddlActive;
        protected System.Web.UI.WebControls.Label lblSignUpDuration;
        protected System.Web.UI.WebControls.TextBox txtSignUpDurationStart;
        protected System.Web.UI.WebControls.TextBox txtSignUpDurationEnd;
        protected System.Web.UI.WebControls.Label lblSchedularName;
        protected System.Web.UI.WebControls.TextBox txtSchedularName;
        protected System.Web.UI.WebControls.Label lblFrequency;
        protected System.Web.UI.WebControls.DropDownList ddlShedularFrequency;
        protected System.Web.UI.WebControls.Label lblSchedularStart;
        protected System.Web.UI.WebControls.TextBox txtSchedularStart;
        protected System.Web.UI.WebControls.Label lblTemplate;
        protected System.Web.UI.WebControls.DropDownList ddlSelectTemplate;
        protected System.Web.UI.WebControls.Label lblFromEmail;
        protected System.Web.UI.WebControls.TextBox txtFromEmail;
        protected System.Web.UI.WebControls.Label lblReplytoEmail;
        protected System.Web.UI.WebControls.TextBox txtReplytoEmail;
        protected System.Web.UI.WebControls.Label lblEmailSubject;
        protected System.Web.UI.WebControls.TextBox txtEmailSubject;
        protected System.Web.UI.WebControls.Label lblEmailBody;
        protected EmailModule.Email.UserControl.HTMLEditor HTMLEditor1;
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.DropDownList ddlPriority;
        protected System.Web.UI.WebControls.Button btnSave;
    }
}
