//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailModule.Email {
    
    public partial class BounceReport {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected EmailModule.Email.UserControl.Menu Menu1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Label lblModule;
        protected System.Web.UI.WebControls.DropDownList ddlModule;
        protected System.Web.UI.WebControls.Label lblBounceCount;
        protected System.Web.UI.WebControls.TextBox txtBounceCount;
        protected System.Web.UI.WebControls.Label lblUnsubscribed;
        protected System.Web.UI.WebControls.DropDownList ddlUnsubscribed;
        protected System.Web.UI.WebControls.Button btnShowReport;
        protected System.Web.UI.WebControls.LinkButton lnkUnsubscribe;
        protected System.Web.UI.WebControls.Label lblUnsMsg;
        protected System.Web.UI.HtmlControls.HtmlGenericControl divNewMod;
        protected System.Web.UI.WebControls.Label lblResultNew;
        protected System.Web.UI.WebControls.GridView gvBounceNewModule;
        protected System.Web.UI.HtmlControls.HtmlGenericControl divOldMod;
        protected System.Web.UI.WebControls.Label lblResultOld;
        protected System.Web.UI.WebControls.GridView gvBounceOldModule;
    }
}
