//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4961
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailModule.Email {
    
    public partial class CreateTemplate {
        protected EmailModule.Email.UserControl.Menu Menu1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Label lblMsg;
        protected System.Web.UI.WebControls.Label lbltemplate;
        protected System.Web.UI.WebControls.TextBox txtTemplate;
        protected System.Web.UI.WebControls.Label lblFromEmail;
        protected System.Web.UI.WebControls.TextBox txtFromEmail;
        protected System.Web.UI.WebControls.Label lblReplyTo;
        protected System.Web.UI.WebControls.TextBox txtReplyTo;
        protected System.Web.UI.WebControls.Label lblEmailSubject;
        protected System.Web.UI.WebControls.TextBox txtEmailSubject;
        protected System.Web.UI.WebControls.Label lblImageSelector;
        protected System.Web.UI.WebControls.DropDownList ddlImageSelector;
        protected System.Web.UI.WebControls.Label lblDupTemplate;
        protected System.Web.UI.WebControls.DropDownList ddlDuplicateTemplate;
        protected System.Web.UI.WebControls.Label lblEmailBody;
        protected EmailModule.Email.UserControl.HTMLEditor HTMLEditor1;
        protected System.Web.UI.WebControls.Button btnSave;
    }
}
