//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailModule.Email {
    
    public partial class EmailSendReport {
        protected EmailModule.Email.UserControl.Menu Menu1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Label lblBatchID;
        protected System.Web.UI.WebControls.DropDownList ddlBatchID;
        protected System.Web.UI.WebControls.Button btnShowReport;
        protected System.Web.UI.WebControls.Label lblBatchReqTime;
        protected System.Web.UI.WebControls.LinkButton lbCancelAll;
        protected System.Web.UI.WebControls.Label lblCancelAll;
        protected System.Web.UI.WebControls.Label lblResult;
        protected System.Web.UI.WebControls.GridView gvEmailSend;
        protected System.Web.UI.WebControls.Label lblFName;
        protected System.Web.UI.WebControls.Label txtFName;
        protected System.Web.UI.WebControls.Label lblLName;
        protected System.Web.UI.WebControls.Label txtLName;
        protected System.Web.UI.WebControls.Label lblEmail;
        protected System.Web.UI.WebControls.Label txtEmail;
        protected System.Web.UI.WebControls.Label lblRegID;
        protected System.Web.UI.WebControls.Label txtRegID;
        protected System.Web.UI.WebControls.Label lblZip;
        protected System.Web.UI.WebControls.Label txtZip;
        protected System.Web.UI.WebControls.Label lblAcive;
        protected System.Web.UI.WebControls.Label txtActive;
        protected System.Web.UI.WebControls.Label lblCompany;
        protected System.Web.UI.WebControls.Label txtCompany;
        protected System.Web.UI.WebControls.Label lblRegister;
        protected System.Web.UI.WebControls.Label lblRegStart;
        protected System.Web.UI.WebControls.Label txtRegStart;
        protected System.Web.UI.WebControls.Label lblRegEnd;
        protected System.Web.UI.WebControls.Label txtRegEnd;
        protected System.Web.UI.WebControls.Label lblBirthDate;
        protected System.Web.UI.WebControls.Label lblBdayStart;
        protected System.Web.UI.WebControls.Label txtBdayStart;
        protected System.Web.UI.WebControls.Label lblBdayEnd;
        protected System.Web.UI.WebControls.Label txtBdayEnd;
        protected System.Web.UI.WebControls.Label lblTemplate;
        protected System.Web.UI.WebControls.Label txtTemplate;
        protected System.Web.UI.WebControls.Label lblFromEmail;
        protected System.Web.UI.WebControls.Label txtFromEmail;
        protected System.Web.UI.WebControls.Label lblReplytoEmail;
        protected System.Web.UI.WebControls.Label txtReplytoEmail;
        protected System.Web.UI.WebControls.Label lblEmailSubject;
        protected System.Web.UI.WebControls.Label txtEmailSubject;
        protected System.Web.UI.WebControls.Label lblEmailBody;
        protected System.Web.UI.WebControls.Label txtEmailBody;
        protected System.Web.UI.WebControls.Label lblScheduleTime;
        protected System.Web.UI.WebControls.Label txtSchedule;
    }
}
