//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4961
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailModule.Email {
    
    public partial class EmailSendSearch {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Label lblError;
        protected System.Web.UI.WebControls.Label lblMsg;
        protected System.Web.UI.WebControls.ValidationSummary vsSearch;
        protected System.Web.UI.WebControls.Label lblSearchFName;
        protected System.Web.UI.WebControls.TextBox txtSearchFName;
        protected System.Web.UI.WebControls.Label lblSearchLName;
        protected System.Web.UI.WebControls.TextBox txtSearchLName;
        protected System.Web.UI.WebControls.Label lblSearchEmail;
        protected System.Web.UI.WebControls.TextBox txtSearchEmail;
        protected System.Web.UI.WebControls.RegularExpressionValidator revEmail;
        protected System.Web.UI.WebControls.Label lblSearchRegID;
        protected System.Web.UI.WebControls.TextBox txtSearchRegID;
        protected System.Web.UI.WebControls.RegularExpressionValidator revRegID;
        protected System.Web.UI.WebControls.Label lblSearchZip;
        protected System.Web.UI.WebControls.TextBox txtSearchZip;
        protected System.Web.UI.WebControls.Label lblSearchBdayHeader;
        protected System.Web.UI.WebControls.Label lblSearchBdayStart;
        protected System.Web.UI.WebControls.DropDownList ddlSearchBdayStartDay;
        protected System.Web.UI.WebControls.DropDownList ddlSearchBdayStartMonth;
        protected System.Web.UI.WebControls.Label lblSearchBdayEnd;
        protected System.Web.UI.WebControls.DropDownList ddlSearchBdayEndDay;
        protected System.Web.UI.WebControls.DropDownList ddlSearchBdayEndMonth;
        protected System.Web.UI.WebControls.Label lblSearchActive;
        protected System.Web.UI.WebControls.DropDownList ddlSearchActive;
        protected System.Web.UI.WebControls.Label lblSearchCompany;
        protected System.Web.UI.WebControls.DropDownList ddlSearchCompany;
        protected System.Web.UI.WebControls.Label lblSearchTemplate;
        protected System.Web.UI.WebControls.DropDownList ddlSearchTemplate;
        protected System.Web.UI.WebControls.Label lblBatchID;
        protected System.Web.UI.WebControls.TextBox txtSearchBatchID;
        protected System.Web.UI.WebControls.RegularExpressionValidator rgvBatchID;
        protected System.Web.UI.WebControls.Label lblSeachStatus;
        protected System.Web.UI.WebControls.DropDownList ddlSeachStatus;
        protected System.Web.UI.WebControls.Label lblSearchRequestHeader;
        protected System.Web.UI.WebControls.Label lblSearchRequestStart;
        protected System.Web.UI.WebControls.TextBox txtSearchRequestStart;
        protected System.Web.UI.WebControls.Label lblSearchRequestEnd;
        protected System.Web.UI.WebControls.TextBox txtSearchRequestEnd;
        protected System.Web.UI.WebControls.Label lblSearchScheduleDateHeader;
        protected System.Web.UI.WebControls.Label lblSearchScheduleStart;
        protected System.Web.UI.WebControls.TextBox txtSearchScheduleStart;
        protected System.Web.UI.WebControls.Label lblSearchScheduleEnd;
        protected System.Web.UI.WebControls.TextBox txtSearchScheduleEnd;
        protected System.Web.UI.WebControls.Label lblSearchSentDateHeader;
        protected System.Web.UI.WebControls.Label lblSearchSentStart;
        protected System.Web.UI.WebControls.TextBox txtSearchSentStart;
        protected System.Web.UI.WebControls.Label lblSearchSentEnd;
        protected System.Web.UI.WebControls.TextBox txtSearchSentEnd;
        protected System.Web.UI.WebControls.Label lblSearchOpenedHeader;
        protected System.Web.UI.WebControls.Label lblSearchOpenedStart;
        protected System.Web.UI.WebControls.TextBox txtSearchOpenedStart;
        protected System.Web.UI.WebControls.Label lblSearchOpenedEnd;
        protected System.Web.UI.WebControls.TextBox txtSearchOpenedEnd;
        protected System.Web.UI.WebControls.Button btnShowReport;
        protected System.Web.UI.WebControls.LinkButton lbExport;
        protected System.Web.UI.WebControls.DropDownList ddlPageSize;
        protected System.Web.UI.WebControls.Label lblResult;
        protected System.Web.UI.WebControls.GridView gvEmailSchedule;
    }
}
