//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4961
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailModule.Email {
    
    public partial class EmailUsers {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Label lblError;
        protected System.Web.UI.WebControls.Label lblMsg;
        protected System.Web.UI.WebControls.ValidationSummary vsSearch;
        protected System.Web.UI.WebControls.Label lblFName;
        protected System.Web.UI.WebControls.TextBox txtFName;
        protected System.Web.UI.WebControls.Label lblLName;
        protected System.Web.UI.WebControls.TextBox txtLName;
        protected System.Web.UI.WebControls.Label lblEmail;
        protected System.Web.UI.WebControls.TextBox txtEmail;
        protected System.Web.UI.WebControls.RegularExpressionValidator revEmail;
        protected System.Web.UI.WebControls.Label lblRegID;
        protected System.Web.UI.WebControls.TextBox txtRegID;
        protected System.Web.UI.WebControls.RegularExpressionValidator revRegID;
        protected System.Web.UI.WebControls.Label lblZip;
        protected System.Web.UI.WebControls.TextBox txtZip;
        protected System.Web.UI.WebControls.Label lblAcive;
        protected System.Web.UI.WebControls.DropDownList ddlActive;
        protected System.Web.UI.WebControls.Label lblCompany;
        protected System.Web.UI.WebControls.DropDownList ddlCompany;
        protected System.Web.UI.WebControls.Label lblAgeRange;
        protected System.Web.UI.WebControls.TextBox txtAgeRangeStart;
        protected System.Web.UI.WebControls.TextBox txtAgeRangeEnd;
        protected System.Web.UI.WebControls.Label lblGender;
        protected System.Web.UI.WebControls.DropDownList ddlGender;
        protected System.Web.UI.WebControls.Label lblRegister;
        protected System.Web.UI.WebControls.Label lblRegStart;
        protected System.Web.UI.WebControls.TextBox txtRegStart;
        protected System.Web.UI.WebControls.Label lblRegEnd;
        protected System.Web.UI.WebControls.TextBox txtRegEnd;
        protected System.Web.UI.WebControls.Label lblBirthDate;
        protected System.Web.UI.WebControls.Label lblBdayStart;
        protected System.Web.UI.WebControls.DropDownList ddlBdayStartDay;
        protected System.Web.UI.WebControls.DropDownList ddlBdayStartMonth;
        protected System.Web.UI.WebControls.Label lblBdayEnd;
        protected System.Web.UI.WebControls.DropDownList ddlBdayEndDay;
        protected System.Web.UI.WebControls.DropDownList ddlBdayEndMonth;
        protected System.Web.UI.WebControls.CheckBox chkOffer;
        protected System.Web.UI.WebControls.Label lblOffer;
        protected System.Web.UI.WebControls.TextBox txtReferrer;
        protected System.Web.UI.WebControls.TextBox txtSentCount;
        protected System.Web.UI.WebControls.TextBox txtOpenedCount;
        protected System.Web.UI.WebControls.TextBox txtOpenRate;
        protected System.Web.UI.WebControls.Button btnSelect;
        protected System.Web.UI.WebControls.LinkButton lbExport;
        protected System.Web.UI.WebControls.Label lblResult;
        protected System.Web.UI.WebControls.GridView gvUsers;
        protected System.Web.UI.WebControls.Label lblTemplate;
        protected System.Web.UI.WebControls.DropDownList ddlSelectTemplate;
        protected System.Web.UI.WebControls.Label lblFromEmail;
        protected System.Web.UI.WebControls.TextBox txtFromEmail;
        protected System.Web.UI.WebControls.Label lblReplytoEmail;
        protected System.Web.UI.WebControls.TextBox txtReplytoEmail;
        protected System.Web.UI.WebControls.Label lblEmailSubject;
        protected System.Web.UI.WebControls.TextBox txtEmailSubject;
        protected System.Web.UI.WebControls.Label lblEmailBody;
        protected EmailModule.Email.UserControl.HTMLEditor HTMLEditor1;
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.DropDownList ddlPriority;
        protected System.Web.UI.WebControls.Label lblScheduleTime;
        protected System.Web.UI.WebControls.RadioButtonList rdbScheduleBy;
        protected System.Web.UI.WebControls.TextBox txtScheduleDate;
        protected System.Web.UI.WebControls.TextBox txtScheduleTime;
        protected System.Web.UI.WebControls.DropDownList ddlScheduleToken;
        protected System.Web.UI.WebControls.CheckBox chkReschedule1;
        protected System.Web.UI.WebControls.Label lblReschedule1;
        protected System.Web.UI.WebControls.DropDownList ddlReschedule1;
        protected System.Web.UI.WebControls.CheckBox chkReschedule2;
        protected System.Web.UI.WebControls.Label lblReschedule2;
        protected System.Web.UI.WebControls.DropDownList ddlReschedule2;
        protected System.Web.UI.WebControls.CheckBox chkReschedule3;
        protected System.Web.UI.WebControls.Label lblReschedule3;
        protected System.Web.UI.WebControls.DropDownList ddlReschedule3;
        protected System.Web.UI.WebControls.CheckBox chkReschedule4;
        protected System.Web.UI.WebControls.Label lblReschedule4;
        protected System.Web.UI.WebControls.DropDownList ddlReschedule4;
        protected System.Web.UI.WebControls.CheckBox chkReschedule5;
        protected System.Web.UI.WebControls.Label lblReschedule5;
        protected System.Web.UI.WebControls.DropDownList ddlReschedule5;
        protected System.Web.UI.WebControls.CheckBox chkReschedule6;
        protected System.Web.UI.WebControls.Label lblReschedule6;
        protected System.Web.UI.WebControls.DropDownList ddlReschedule6;
        protected System.Web.UI.WebControls.Button btnSendMail;
    }
}
