//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailModule.Email {
    
    public partial class SendEMail {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Label lblError;
        protected System.Web.UI.WebControls.Label lblUserIDs;
        protected System.Web.UI.WebControls.TextBox txtUserIDs;
        protected System.Web.UI.WebControls.Label lblTemplate;
        protected System.Web.UI.WebControls.DropDownList ddlSelectTemplate;
        protected System.Web.UI.WebControls.Label lblFromEmail;
        protected System.Web.UI.WebControls.TextBox txtFromEmail;
        protected System.Web.UI.WebControls.Label lblEmailSubject;
        protected System.Web.UI.WebControls.TextBox txtEmailSubject;
        protected System.Web.UI.WebControls.Label lblEmailBody;
        protected EmailModule.Email.UserControl.HTMLEditor HTMLEditor1;
        protected System.Web.UI.WebControls.Button btnSendMail;
    }
}
