//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4961
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailModule.Email {
    
    public partial class TAFAutoNotifyer {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected EmailModule.Email.UserControl.Menu Menu1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.LinkButton lnkBtnExport;
        protected System.Web.UI.WebControls.Button btnShowReport;
        protected System.Web.UI.WebControls.GridView GridView1;
        protected System.Web.UI.WebControls.SqlDataSource SqlDataSource1;
    }
}
