//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailModule.Email {
    
    public partial class TellYourFriends {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Label lblError;
        protected System.Web.UI.WebControls.TextBox txtYourName;
        protected System.Web.UI.WebControls.TextBox txtYourEmail;
        protected System.Web.UI.WebControls.TextBox txtFirstFriendName;
        protected System.Web.UI.WebControls.TextBox txtFirstFriendEmail;
        protected System.Web.UI.WebControls.TextBox txtSecondFriendName;
        protected System.Web.UI.WebControls.TextBox txtSecondFriendEmail;
        protected System.Web.UI.WebControls.TextBox txtThirdFriendName;
        protected System.Web.UI.WebControls.TextBox txtThirdFriendEmail;
        protected System.Web.UI.WebControls.TextBox txtEmailSubject;
        protected EmailModule.Email.UserControl.HTMLEditor HTMLEditor1;
        protected System.Web.UI.WebControls.Button btnSubmit;
    }
}
