//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailModule.Email {
    
    public partial class UploadGiftCerts {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected EmailModule.Email.UserControl.Menu Menu1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Label lblMsg;
        protected System.Web.UI.WebControls.Label lblError;
        protected System.Web.UI.WebControls.Label lblCert1;
        protected System.Web.UI.WebControls.FileUpload FileUpload1;
        protected System.Web.UI.WebControls.Label lblCert2;
        protected System.Web.UI.WebControls.FileUpload FileUpload2;
        protected System.Web.UI.WebControls.Label lblCert3;
        protected System.Web.UI.WebControls.FileUpload FileUpload3;
        protected System.Web.UI.WebControls.Label lblCert4;
        protected System.Web.UI.WebControls.FileUpload FileUpload4;
        protected System.Web.UI.WebControls.Label lblCert5;
        protected System.Web.UI.WebControls.FileUpload FileUpload5;
        protected System.Web.UI.WebControls.Button btnSave;
        protected System.Web.UI.WebControls.Label lblDelMsg;
        protected System.Web.UI.WebControls.Label lblDelError;
        protected System.Web.UI.WebControls.Label lblImageSelector;
        protected System.Web.UI.WebControls.DropDownList ddlImageSelector;
        protected System.Web.UI.WebControls.Button btnDel;
    }
}
