//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailModule.TAF {
    
    public partial class TAFadmin {
        protected EmailModule.Email.UserControl.Menu Menu2;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Label lblYouTube;
        protected System.Web.UI.WebControls.TextBox txtYouTube;
        protected System.Web.UI.WebControls.Label lblImageSelector;
        protected System.Web.UI.WebControls.DropDownList ddlImageSelector;
        protected System.Web.UI.WebControls.Label lblSubject;
        protected System.Web.UI.WebControls.TextBox txtSubject;
        protected System.Web.UI.WebControls.Label lblBody;
        protected EmailModule.Email.UserControl.HTMLEditor HTMLEditor1;
        protected System.Web.UI.WebControls.Button btnUpdate;
    }
}
