//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailModule.TAF {
    
    public partial class TAFCertificate {
        protected EmailModule.Email.UserControl.Menu Menu2;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Label lblGiftCert;
        protected System.Web.UI.WebControls.DropDownList ddlGiftCert;
        protected System.Web.UI.WebControls.Label lblZip;
        protected System.Web.UI.WebControls.TextBox txtZip;
        protected System.Web.UI.WebControls.Button btnSaveGiftCert;
        protected System.Web.UI.WebControls.Label lblCancelAll;
        protected System.Web.UI.WebControls.Label lblResult;
        protected System.Web.UI.WebControls.GridView gvTAFCert;
    }
}
